from chess.exception.chess_exception import ChessException


